- name: Pull Docker Image of Calculator
  hosts: host_machine
  tasks:
    - name: removing old containers
      shell: docker ps -aq --filter name="calculator" | xargs docker stop | xargs docker rm

    - name: Pull image
      shell: docker pull dockervatsal/calculator:latest

    - name: Run container
      shell: docker run -i -t --name calculator -d dockervatsal/calculator