- name: Pull Docker Image of Calculator
  hosts: host_machine
  tasks:
    - name: removing old containers
      shell: if docker ps -aq -f "name=calculator" | grep -q .; then docker ps -aq -f "name=calculator" | xargs docker stop; docker ps -aq -f "name=calculator" | xargs docker rm; else echo "No containers with the name 'calculator' found."; fi

    - name: Pull image
      shell: docker pull dockervatsal/calculator:latest

    - name: Run container
      shell: docker run -i -t --name calculator -d dockervatsal/calculator